### ISSUE TITLE
Preliminary Circuit Protection Design

### ISSUE THREAD

**Issue by codeThatThinks** [csinko/io-master#1]
- Research what kinds of things I/O pins need to be protected against
- Research possible protection circuits
- Begin preliminary schematic of protection subsystem

**Comment by nuntch** [comment]
This is what I have so far:
Over voltage protection
Over current protection
Accidental grounding
Reverse polarity protection

**Comment by nuntch** [comment]
Weekly update:
I have a circuit sketched to protect against reverse polarity and over current issues.
I won't be back in town until about noon today. 

This week i will be taking my schematic and begin creating the design in kiCad.
