### ISSUE TITLE
Make a short writeup about the GUI

### ISSUE THREAD

**Issue by csinko** [csinko/io-master#10]
This will be put into the readme and be used for preliminary design presentations and discussions.

Cover what this component is responsible for, what it adds to the design of the project, and some challenges that will arise.  Also cover any preliminary design ideas that exist.

**Comment by Metalison** [comment]
The purpose of the GUI interface is to create a user friendly yet customizable program to help users tell the micro-controller to use whatever protocols that the user wishes to use from the provided list. The interface will include drop down menus to adjust the protocol that the board will use.  This interface will also allow the user to select what information they want to send through the device as well as start and stop the flow of information through the device. The GUI will also define the hardware pins and clock speeds needed to run whichever protocol is selected. This includes setting the voltage levels that the board will expect to see. This will define what is seen as a 1 or a 0. The gui will most likely be done using python. Possible challenges include figuring out which GUI base to use in python. Possible options are appJar, TkInter, PyQT, or Kivy. More research will be done on each to figure out which one is best suited for this project.

**Comment by csinko** [comment]
Looks good
