### ISSUE TITLE
Research GUI options for Python

### ISSUE THREAD

**Issue by csinko** [csinko/io-master#4]
We will want a UI for users to define, edit, and select protocols for our tool.  Users will need to be able to

- Define clock signal speeds
- Set expected voltage levels
- Define ranges for a logic 0 and a logic 1
- Give names and descriptions for protocols
- Select protocols being used, assign pins
- Select data to send
- Start and stop the device, along with other operations

There are a few options I am aware of that can be used for GUIs in Python
PyQT
Tkinter
Kivy

Do research and testing on these frameworks, and get a feel for making GUI elements with Python.  Decide the pros and cons of all the frameworks you test, and we will decide which one to use officially for the project.

**Comment by codeThatThinks** [comment]
Check out ```guizero```, it's a Python library that makes it much easier to use TkInter. https://lawsie.github.io/guizero/

**Comment by Metalison** [comment]
Weekly Update:
Started practicing using tkinter. A window appears and it has words and buttons that work.

**Comment by nuntch** [comment]
See google drive for the requirements needed for GUI sketch. 
Due by our next meeting with French. 10/17/19
