### ISSUE TITLE
Research and Test Clock Inputs with MCU

### ISSUE THREAD

**Issue by csinko** [csinko/io-master#5]
We will need to be able to patch in and switch between different frequencies for the project.   The MCU has the ability to use an external clock, but we need the flexibility to set these clocks and assign them to various I/O lines (potentially multiple lines simultaneously.

Learn how to read in and use external clock signals, make a test application to utilize external clock signals, and determine how we can control where a clock signal connects to, whether its through software routing or hardware routing (mux, demux, etc.)

**Comment by WhoDaWhatNow** [comment]
STM32H743 Datasheet link: https://www.st.com/resource/en/datasheet/stm32h743bi.pdf
page 126 talks about clock inputs

STM Timers: https://www.st.com/content/ccc/resource/technical/document/application_note/group0/91/01/84/3f/7c/67/41/3f/DM00236305/files/DM00236305.pdf/jcr:content/translations/en.DM00236305.pdf
