### ISSUE TITLE
Make a short writeup about the I/O Level Shifting And Logic

### ISSUE THREAD

**Issue by csinko** [csinko/io-master#7]
This will be put into the readme and be used for preliminary design presentations and discussions.

Cover what this component is responsible for, what it adds to the design of the project, and some challenges that will arise.  Also cover any preliminary design ideas that exist.

**Comment by codeThatThinks** [comment]
The Level Shifting and Logic Subsystem is responsible for providing electrical conversion between the microcontroller interface and the device under test. This includes acting as an output and input to the microcontroller, providing logic-high, logic-low, and floating output states, bidirectional logic-level conversion, and capability to drive/receive differential or single-ended lines. This block should be fully configurable via control signals from the microcontroller. This includes setting the high and low voltages, optional pull-up/pull-down resistors, and multiplexing the line between single-ended and differential hardware. Design challenges include implementing a bidirectional differential transceiver and ensuring that multiplexing does not affect high speed operation.
