### ISSUE TITLE
Make a short writeup about the MCU power and interface

### ISSUE THREAD

**Issue by csinko** [csinko/io-master#8]
This will be put into the readme and be used for preliminary design presentations and discussions.

Cover what this component is responsible for, what it adds to the design of the project, and some challenges that will arise.  Also cover any preliminary design ideas that exist.

**Comment by WhoDaWhatNow** [comment]
MCU Power and Interface is responsible for receiving configuration and executing commands. These commands will come through the serial bus and need to be parsed/decoded. Execution will include adjusting the clock speed, target voltage levels, and re-configuring pins as specified by the commands received.

These capabilities will be crucial for switching between protocols on the multi-use pins. The challenges will be primarily with creating a good control scheme for managing all the necessary multiplexers to route signals to all the proper pins, at the correct speed and voltages.

**Comment by WhoDaWhatNow** [comment]
@csinko Is this good?

**Comment by csinko** [comment]
looks good
